/**
 * Common constants for all features.
 */
export default class CommonConstants {
  /**
   * The width or height of the component is spread across the parent component.
   */
  static readonly FULL_PARENT = '100%';

  /**
   * Input length of the account.
   */
  static readonly INPUT_ACCOUNT_LENGTH = 11;

  static readonly INPUT_PASSWORD_LENGTH = 11;

  /**
   * Image back margin left of the 7.2.
   */
  static readonly BACK_MARGIN_LEFT: string = '4.2%';
  /**
   * Image back margin top of the 19.
   */
  static readonly BACK_MARGIN_TOP: number = 19;
  /**
   *  Left padding of the input box
   */
  static readonly INPUT_PADDING_LEFT = 10;

  /** 登录获取验证码间隔  */
  static readonly GET_MSG_CODE_INTERVAL = 30;
}